### ISSUE TITLE
iis_site - wrong number of arguments

### ISSUE THREAD

**Issue by drpebcak** [chef-cookbooks/iis#215]
I'm getting this error when using the `iis_site` resource:

```
  * iis_site[ExternalAPI] action add[2015-09-22T17:27:35-07:00] INFO: Processing
 iis_site[ExternalAPI] action add (tb-iis::ExternalAPI line 52)


    ============================================================================
====
    Error executing action `add` on resource 'iis_site[ExternalAPI]'
    ============================================================================
====

    ArgumentError
    -------------
    wrong number of arguments (0 for 1)

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/iis/libraries/helper.rb:80:in `appcmd'
    c:/chef/cache/cookbooks/iis/providers/site.rb:57:in `block in class_from_fil
e'

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/tb-iis/recipes/ExternalAPI.rb

     52: iis_site 'ExternalAPI' do
     53:   path "#{node['iis']['pubroot']}/#{node['tb-iis']['externalapi']['web_
dir']}"
     54:   application_pool 'ExternalAPI'
     55:   bindings site_bindings
     56:   action [:add, :config, :start]
     57: end

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/tb-iis/recipes/ExternalAPI.rb:52:in `f
rom_file'

    iis_site("ExternalAPI") do
      action [:add, :config, :start]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :iis_site
      cookbook_name "tb-iis"
      recipe_name "ExternalAPI"
      path "D:/inetpub/api"
      application_pool "ExternalAPI"
      bindings "http/*:qa-api.redacted.net:80,http/*:api.redacted.com:80"
      site_name "ExternalAPI"
    end

[2015-09-22T17:27:35-07:00] INFO: Running queued delayed notifications before re
-raising exception

Running handlers:
[2015-09-22T17:27:35-07:00] ERROR: Running exception handlers
  - SensuCleaner
Running handlers complete
[2015-09-22T17:27:35-07:00] ERROR: Exception handlers complete
Chef Client failed. 13 resources updated in 100.504749 seconds
[2015-09-22T17:27:35-07:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stack
trace.out
[2015-09-22T17:27:35-07:00] FATAL: ArgumentError: iis_site[ExternalAPI] (tb-iis:
:ExternalAPI line 52) had an error: ArgumentError: wrong number of arguments (0
for 1)
```

Here is what my wrapper looks like:

```
iis_site 'ExternalAPI' do
  path "#{node['iis']['pubroot']}/#{node['tb-iis']['externalapi']['web_dir']}"
  application_pool 'ExternalAPI'
  bindings site_bindings
  action [:add, :config, :start]
end
```

Any idea what is happening here? I started experiencing this after updating to version 4.1.1 of the iis cookbook.

**Comment by drpebcak** [comment]
Not 100% sure what was going on, but I resolved it by pulling latest from master.
