### ISSUE TITLE
Release 4.1.8

### ISSUE THREAD

**Issue by spuder** [chef-cookbooks/iis#278]
Can we get version 4.1.8 released? 

There are commits that say "release 4.1.8" and the metadata shows 4.1.8, yet supermarket and github tags only have 4.1.7

https://github.com/chef-cookbooks/iis/commits/master

https://supermarket.chef.io/cookbooks/iis

This warning is still showing up. It was fixed, but not until after version 4.1.7 was pushed

```
    - c:/chef/cache/cookbooks/iis/resources/pool.rb:78:in `class_from_file'
  Default value nil is invalid for property config of resource ingredient_config. Possible fixes: 1. Remove 'default: ni
l' if nil means 'undefined'. 2. Set a valid default value if there is a reasonable one. 3. Allow nil as a valid value of
 your property (for example, 'property :config, [ String, nil ], default: nil'). Error: Property config must be one of:
String!  You passed nil. at 1 location:
    - c:/chef/cache/cookbooks/chef-ingredient/resources/ingredient_config.rb:28:in `class_from_file'
                                                                                                                  
```

**Comment by tas50** [comment]
4.1.8 is released now
