### ISSUE TITLE
Cookbook Unable to Install Windows Features on Chef Client 14

### ISSUE THREAD

**Issue by joshburt** [chef-cookbooks/iis#419]
### Preface
As per https://docs.chef.io/release_notes.html#what-s-new-in-14-0-202
```
windows_feature
Use the windows_feature resource to add, remove or entirely delete Windows features and roles. This resource calls the windows_feature_dism or windows_feature_powershell resources depending on the specified installation method, and defaults to DISM, which is available on both Workstation and Server editions of Windows. This resource was ported from the windows community cookbook.

Note
These resources received significant refactoring in the 4.0 version of the windows cookbook (March 2018). windows_feature resources will now fail if the installation of invalid features is requested, and support for installation via server servermanagercmd.exe has been removed. If you are using a windows_cookbook version less than 4.0, you may need to update cookbooks for Chef 14.
```

### Cookbook Versions
IIS Cookbook Version: 6.8.1
Windows Cookbook Version: 4.2.1

### Chef-client version
14.0.202

### Platform Details
Windows Server 2016 Core

### Scenario:
We are attempting to install IIS using the latest Chef Client (14).
Note that the prior Chef Client (13.8.5) works as expected.

### Steps to Reproduce:
A simple runlist will demonstrate the issue: 'recipe[iis]'

### Expected Result:
IIS should get installed.

### Actual Result:
Convergence fails with the following messages:

```
Compiling Cookbooks...
Converging 2 resources
Recipe: iis::default
  * windows_feature[IIS-WebServerRole] action install[2018-04-23T12:50:05-06:00] INFO: Processing windows_feature[IIS-WebServerRole] action install (iis::default line 25)

    * windows_feature_dism[IIS-WebServerRole] action install[2018-04-23T12:50:05-06:00] INFO: Processing windows_feature_dism[IIS-WebServerRole] action install (C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/resource/windows_feature.rb line 83)


      ================================================================================
      Error executing action `install` on resource 'windows_feature_dism[IIS-WebServerRole]'
      ================================================================================

      RuntimeError
      ------------
      The Windows feature iis-webserverrole is not available on this version of Windows. Run 'dism /online /Get-Features' to see the list of available feature names.

      Resource Declaration:
      ---------------------
      # In C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/resource/windows_feature.rb

       83:           declare_resource(subresource, new_resource.name) do
       84:             action desired_action
       85:             feature_name new_resource.feature_name
       86:             source new_resource.source if new_resource.source
       87:             all new_resource.all
       88:             timeout new_resource.timeout
       89:             management_tools new_resource.management_tools if subresource == :windows_feature_powershell
       90:           end
       91:         end

      Compiled Resource:
      ------------------
      # Declared in C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/resource/windows_feature.rb:83:in `run_default_subresource'

      windows_feature_dism("IIS-WebServerRole") do
        action [:install]
        default_guard_interpreter :default
        declared_type :windows_feature_dism
        cookbook_name "iis"
        feature_name ["iis-webserverrole"]
        all true
        timeout 600
      end

      System Info:
      ------------
      chef_version=14.0.202
      platform=windows
      platform_version=10.0.14393
      ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [i386-mingw32]
      program_name=C:/opscode/chef/bin/chef-client
      executable=C:/opscode/chef/bin/chef-client

[2018-04-23T12:50:05-06:00] INFO: Running queued delayed notifications before re-raising exception

    ================================================================================
    Error executing action `install` on resource 'windows_feature[IIS-WebServerRole]'
    ================================================================================

    RuntimeError
    ------------
    windows_feature_dism[IIS-WebServerRole] (C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/resource/windows_feature.rb line 83) had an error: RuntimeError: The Windows feature iis-webserverrole is not available on this version of Windows. Run 'dism /online /Get-Features' to see the list of available feature names.

    Resource Declaration:
    ---------------------
    # In c:/chefinstall/.chef/local-mode-cache/cache/cookbooks/iis/recipes/default.rb

     25:   windows_feature feature do
     26:     action :install
     27:     all !Opscode::IIS::Helper.older_than_windows2012?
     28:     source node['iis']['source'] unless node['iis']['source'].nil?
     29:   end
     30: end

    Compiled Resource:
    ------------------
    # Declared in c:/chefinstall/.chef/local-mode-cache/cache/cookbooks/iis/recipes/default.rb:25:in `block in from_file'

    windows_feature("IIS-WebServerRole") do
      action [:install]
      default_guard_interpreter :default
      declared_type :windows_feature
      cookbook_name "iis"
      recipe_name "default"
      all true
      feature_name "IIS-WebServerRole"
    end

    System Info:
    ------------
    chef_version=14.0.202
    platform=windows
    platform_version=10.0.14393
    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [i386-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client

[2018-04-23T12:50:05-06:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2018-04-23T12:50:05-06:00] ERROR: Running exception handlers
Running handlers complete
[2018-04-23T12:50:05-06:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 07 seconds
[2018-04-23T12:50:05-06:00] FATAL: Stacktrace dumped to c:/chefinstall/.chef/local-mode-cache/cache/chef-stacktrace.out
[2018-04-23T12:50:05-06:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-04-23T12:50:05-06:00] FATAL: RuntimeError: windows_feature[IIS-WebServerRole] (iis::default line 25) had an error: RuntimeError: windows_feature_dism[IIS-WebServerRole] (C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.0.202-universal-mingw32/lib/chef/resource/windows_feature.rb line 83) had an error: RuntimeError: The Windows feature iis-webserverrole is not available on this version of Windows. Run 'dism /online /Get-Features' to see the list of available feature names.
```

**Comment by EasyAsABC123** [comment]
just to confirm it isn't similar to this issue? https://github.com/chef-cookbooks/iis/issues/315

It does appear Chef 14 changes `windows_feature` and this might need to be looked at, i am away on business and don't know if i'll have time to look at this so just trying to accumulate more data.

**Comment by joshburt** [comment]
I'll review #315 now and see if its related.

**Comment by EasyAsABC123** [comment]
thank you, i appreciate the assistance on this and patience.

**Comment by joshburt** [comment]
1. I performed an install of .NET 4.7.1 via the .NET Framework 4.7.1 offline installer for Windows (NDP471-KB4033342-x86-x64-AllOS-ENU.exe).
2. Rebooted
3. Started the example chef run with the single item in the runlist 'recipe[iis]'

The issue is still present.  The error that is produced in both scenarios is also slightly different.  I think these are different issues, but definitely around the same features.

The resource used to process the role within this cookbook looks correct.  I'll generate a sample that calls windows_feature directly and try to rule out the IIS cookbook completely next.  I'll post an update soon.

Thanks!

**Comment by joshburt** [comment]
Yep this is just broken in Chef 140.202.  I'm able to reproduce the issue outside of the IIS cookbook.

This is enough to cause the issue:
```
windows_feature 'IIS-WebServerRole' do
  all true
  action :install
end
```
I'll head over to  that repo next and get a bug submitted.  Feel free to leave this open for reference/search as I suspect we'll see this reported until the bug is addressed within the chef client.

**Comment by EasyAsABC123** [comment]
will do! thanks a ton for the due diligence and effort.

**Comment by joshburt** [comment]
I've submitted the issue (https://github.com/chef/chef/issues/7177) to the chef-client repo.

**Comment by EasyAsABC123** [comment]
the resolution in the attached issue is to switch to the 64 bit installer, https://github.com/chef/chef/issues/7177

**Comment by EasyAsABC123** [comment]
actually @joshburt do we need to add `install_method :windows_feature_powershell` if on windows server 2016?

**Comment by stuartpreston** [comment]
@EasyAsABC123 Yes you do, dism is still the default install method for windows_feature across all platforms.
